/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UOpj7x+spJm0PpPNMIh/zb1wAugUiCEHWy5PJs9x+w90KwiCYRO93VE6FfBRAj3SeQFf8ce5plsfJnqHmBY7pg==
 */

/* eslint-disable */
// tslint:disable

import User, {User_InsertParameters} from './user'

interface DatabaseSchema {
  user: {record: User, insert: User_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  User,
  User_InsertParameters,
}
