/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: GxPE+vRHeUvLIRja2TRtKlQw7JeRHXrOgiZ+yeCxUDgIMsJNvbXZ4Nt6/xO8BWPsaSRRT4gbCwcKqpxr4dq76g==
 */

/* eslint-disable */
// tslint:disable

interface User {
  createdAt: Date
  fullName: string
  /**
   * @default nextval('eventsourcing.user_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'user_id'}
  username: string
}
export default User;

interface User_InsertParameters {
  createdAt: Date
  fullName: string
  /**
   * @default nextval('eventsourcing.user_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'user_id'}
  username: string
}
export type {User_InsertParameters}
